Spam ham project using BOW 


1. Preprocessing and Cleaning
2. Bow and TF_IDF (sentences-vectors)
3. Train Test Split
4. Trained our models

should ve done 3 first then 2 by doing this we are preventing data leakage

In [2]:
import pandas as pd
messages=pd.read_csv(r"D:\maths-naik\code_ml\SMSSpamCollection",sep='\t',names=['label','message'])

In [3]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# Data cleaning and preprocessing
import re
import nltk 

In [5]:
from nltk.corpus import stopwords 
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [6]:
corpus=[]

# input features
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)


In [7]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [8]:
y=pd.get_dummies(messages['label'],dtype=int)

In [9]:
# Train Test Split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20,random_state=0)

In [10]:
# creating  bag of words

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [12]:
len(x_train)

4457

In [13]:
x_train=cv.fit_transform(x_train).toarray()

In [17]:
x_test=cv.transform(x_test).toarray()
# why no fit transform for x_test
# because we have already fit the model on x_train so we dont need to fit it again

In [15]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
cv.vocabulary_

{'good': 882,
 'movi': 1400,
 'ok': 1507,
 'leav': 1170,
 'free': 768,
 'give': 844,
 'otherwis': 1546,
 'someth': 1948,
 'mayb': 1310,
 'bit': 177,
 'hope': 1006,
 'got': 897,
 'home': 1002,
 'babe': 131,
 'still': 2000,
 'awak': 122,
 'sinc': 1910,
 'alreadi': 54,
 'workin': 2439,
 'get': 824,
 'job': 1096,
 'said': 1808,
 'matter': 1302,
 'mind': 1344,
 'say': 1823,
 'oh': 1504,
 'yeah': 2482,
 'diet': 556,
 'oh yeah': 1506,
 'sorri': 1958,
 'thing': 2119,
 'may': 1309,
 'pub': 1690,
 'later': 1152,
 'ill': 1045,
 'call': 242,
 'even': 660,
 'idea': 1039,
 'dear': 524,
 'reach': 1721,
 'room': 1791,
 'dear reach': 528,
 'look': 1227,
 'daddi': 498,
 'want': 2346,
 'eat': 617,
 'night': 1466,
 'long': 1224,
 'chennai': 334,
 'sure': 2051,
 'pick': 1597,
 'us': 2295,
 'competit': 408,
 'da': 495,
 'car': 287,
 'park': 1560,
 'da car': 496,
 'okay': 1518,
 'soon': 1955,
 'best': 165,
 'yar': 2476,
 'els': 628,
 'thk': 2127,
 'sort': 1962,
 'funni': 803,
 'yup': 2498,
 'izzit': 1086,
 '

In [40]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
# convert the label to binary using get dummies
# using one hot encoding
y=pd.get_dummies(messages['label'],dtype=int)

In [17]:
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [20]:
y_train=y_train.iloc[:,1].values
# why its true or false isntead of 1 0
y_test=y_test.iloc[:,1].values
# why its true or false isntead of 1 0

In [21]:
y_train.shape

(4457,)

In [18]:
print(y.shape)

(5572, 2)


In [84]:
# Train Test Split

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [22]:
# use naive bayes which is good for text classification in sparse matrix

from sklearn.naive_bayes import MultinomialNB

spam_detect_model=MultinomialNB()

In [23]:
y_train.shape

(4457,)

In [24]:
spam_detect_model.fit(x_train,y_train)

MultinomialNB()

In [25]:
y_pred=spam_detect_model.predict(x_test)

In [26]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       955
           1       0.97      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [28]:
accuracy_score(y_test,y_pred)

0.9856502242152466

In [30]:
confusion_matrix(y_test,y_pred)

array([[950,   5],
       [ 11, 149]], dtype=int64)

In [31]:
# tf idf model 

from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=2500,ngram_range=(1,2))   

In [12]:
x=tf.fit_transform(corpus).toarray()

In [13]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [23]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(x_train,y_train)
# use naive bayes which is good for text classification in sparse matrix

MultinomialNB()

In [24]:
y_pred=model.predict(x_test)

In [25]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [26]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       1.00      0.85      0.92       160

    accuracy                           0.98      1115
   macro avg       0.99      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [28]:
print(accuracy_score(y_test,y_pred))    

0.97847533632287


In [29]:
print(confusion_matrix(y_test,y_pred))

[[955   0]
 [ 24 136]]


In [31]:
from nltk.stem import WordNetLemmatizer
# lammatised import 

lt=WordNetLemmatizer()

In [43]:
corpus_lemmatised=[]

# input features
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    
    review=[lt.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus_lemmatised.append(review)


In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
corpus_lemmatised

[]

In [39]:
tf=TfidfVectorizer(max_features=2500,ngram_range=(1,2)) 

In [44]:
x=tf.fit_transform(corpus_lemmatised).toarray()

In [45]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)   

In [46]:
model=MultinomialNB()
model.fit(x_train,y_train)


MultinomialNB()

In [47]:
y_pred=model.predict(x_test)


In [48]:
print(classification_report(y_test,y_pred)) 

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       0.99      0.85      0.92       160

    accuracy                           0.98      1115
   macro avg       0.98      0.92      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [49]:
print(accuracy_score(y_test,y_pred))

0.9775784753363229
